name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Publish and Release
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: jekyll_remote_plantuml_plugin
          bump-minor-pre-major: true
          version-file: "lib/jekyll_remote_plantuml_plugin/version.rb"

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        if: ${{ steps.release.outputs.release_created }}
